/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.app.ondevicepersonalization;

import android.annotation.Nullable;
import android.content.ContentValues;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * Data to be logged in the EVENTS table that is associated with a pre-existing
 * {@link RequestLogRecord} that has been written to the REQUESTS table.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class EventLogRecord implements Parcelable {
    /**
     * The index of the row in an existing {@link RequestLogRecord} that this payload should be
     * associated with.
     **/
    private int mRowIndex = 0;

    /**
     * The service-assigned type that identifies this payload. Unique for each row. Duplicates are
     * discarded. Must be >0 and <128.
     */
    private int mType = 0;

    /** Additional data to be logged. */
    @Nullable ContentValues mData = null;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/app/ondevicepersonalization/EventLogRecord.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ EventLogRecord(
            int rowIndex,
            int type,
            @Nullable ContentValues data) {
        this.mRowIndex = rowIndex;
        this.mType = type;
        this.mData = data;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * The index of the row in an existing {@link RequestLogRecord} that this payload should be
     * associated with.
     */
    @DataClass.Generated.Member
    public int getRowIndex() {
        return mRowIndex;
    }

    /**
     * The service-assigned type that identifies this payload. Unique for each row. Duplicates are
     * discarded. Must be >0 and <128.
     */
    @DataClass.Generated.Member
    public int getType() {
        return mType;
    }

    /**
     * Additional data to be logged.
     */
    @DataClass.Generated.Member
    public @Nullable ContentValues getData() {
        return mData;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(EventLogRecord other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        EventLogRecord that = (EventLogRecord) o;
        //noinspection PointlessBooleanExpression
        return true
                && mRowIndex == that.mRowIndex
                && mType == that.mType
                && java.util.Objects.equals(mData, that.mData);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + mRowIndex;
        _hash = 31 * _hash + mType;
        _hash = 31 * _hash + java.util.Objects.hashCode(mData);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@android.annotation.NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mData != null) flg |= 0x4;
        dest.writeByte(flg);
        dest.writeInt(mRowIndex);
        dest.writeInt(mType);
        if (mData != null) dest.writeTypedObject(mData, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ EventLogRecord(@android.annotation.NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        int rowIndex = in.readInt();
        int type = in.readInt();
        ContentValues data = (flg & 0x4) == 0 ? null : (ContentValues) in.readTypedObject(ContentValues.CREATOR);

        this.mRowIndex = rowIndex;
        this.mType = type;
        this.mData = data;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @android.annotation.NonNull Parcelable.Creator<EventLogRecord> CREATOR
            = new Parcelable.Creator<EventLogRecord>() {
        @Override
        public EventLogRecord[] newArray(int size) {
            return new EventLogRecord[size];
        }

        @Override
        public EventLogRecord createFromParcel(@android.annotation.NonNull android.os.Parcel in) {
            return new EventLogRecord(in);
        }
    };

    /**
     * A builder for {@link EventLogRecord}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private int mRowIndex;
        private int mType;
        private @Nullable ContentValues mData;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * The index of the row in an existing {@link RequestLogRecord} that this payload should be
         * associated with.
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setRowIndex(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mRowIndex = value;
            return this;
        }

        /**
         * The service-assigned type that identifies this payload. Unique for each row. Duplicates are
         * discarded. Must be >0 and <128.
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setType(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mType = value;
            return this;
        }

        /**
         * Additional data to be logged.
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setData(@android.annotation.NonNull ContentValues value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mData = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull EventLogRecord build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mRowIndex = 0;
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mType = 0;
            }
            if ((mBuilderFieldsSet & 0x4) == 0) {
                mData = null;
            }
            EventLogRecord o = new EventLogRecord(
                    mRowIndex,
                    mType,
                    mData);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1687977508732L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/app/ondevicepersonalization/EventLogRecord.java",
            inputSignatures = "private  int mRowIndex\nprivate  int mType\n @android.annotation.Nullable android.content.ContentValues mData\nclass EventLogRecord extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
