/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.app.ondevicepersonalization;

import android.annotation.NonNull;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.List;
import java.util.Map;

/**
 * User data for personalized ads targeting.
 *
 * @hide
 */
// This class should be updated with the Kotlin mirror
// {@link com.android.ondevicepersonalization.services.policyengine.data.UserData}.
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class UserData implements Parcelable {
    /** The current timestamp in second. */
    long mTimestampSec;

    /** The device timezone +/- minutes offset from UTC. */
    int mTimezoneUtcOffsetMins;

    /** The device orientation. */
    int mOrientation;

    /** The available space on device in MB. */
    long mAvailableStorageMB;

    /** Battery percentage. */
    int mBatteryPercentage;

    /** Carrier. See the full list {@link Carrier}. */
    int mCarrier;

    /** Network connection types. See full list {@link RawUserData.ConnectionType}. */
    int mConnectionType;

    /** Connection speed in kbps. */
    long mNetworkConnectionSpeedKbps;

    /** Status if network is metered. False - not metered. True - metered. */
    boolean mNetworkMetered;

    /** The history of installed/uninstalled packages. */
    @NonNull Map<String, AppInstallStatus> mAppInstalledHistory;

    /** The app usage history in the last 30 days, sorted by total time spent. */
    @NonNull List<AppUsageStatus> mAppUsageHistory;

    /** The most recently known location. */
    @NonNull Location mCurrentLocation;

    /** The location history in last 30 days, sorted by the stay duration. */
    @NonNull List<LocationStatus> mLocationHistory;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/UserData.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ UserData(
            long timestampSec,
            int timezoneUtcOffsetMins,
            int orientation,
            long availableStorageMB,
            int batteryPercentage,
            int carrier,
            int connectionType,
            long networkConnectionSpeedKbps,
            boolean networkMetered,
            @NonNull Map<String,AppInstallStatus> appInstalledHistory,
            @NonNull List<AppUsageStatus> appUsageHistory,
            @NonNull Location currentLocation,
            @NonNull List<LocationStatus> locationHistory) {
        this.mTimestampSec = timestampSec;
        this.mTimezoneUtcOffsetMins = timezoneUtcOffsetMins;
        this.mOrientation = orientation;
        this.mAvailableStorageMB = availableStorageMB;
        this.mBatteryPercentage = batteryPercentage;
        this.mCarrier = carrier;
        this.mConnectionType = connectionType;
        this.mNetworkConnectionSpeedKbps = networkConnectionSpeedKbps;
        this.mNetworkMetered = networkMetered;
        this.mAppInstalledHistory = appInstalledHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mAppInstalledHistory);
        this.mAppUsageHistory = appUsageHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mAppUsageHistory);
        this.mCurrentLocation = currentLocation;
        AnnotationValidations.validate(
                NonNull.class, null, mCurrentLocation);
        this.mLocationHistory = locationHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mLocationHistory);

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * The current timestamp in second.
     */
    @DataClass.Generated.Member
    public long getTimestampSec() {
        return mTimestampSec;
    }

    /**
     * The device timezone +/- minutes offset from UTC.
     */
    @DataClass.Generated.Member
    public int getTimezoneUtcOffsetMins() {
        return mTimezoneUtcOffsetMins;
    }

    /**
     * The device orientation.
     */
    @DataClass.Generated.Member
    public int getOrientation() {
        return mOrientation;
    }

    /**
     * The available space on device in MB.
     */
    @DataClass.Generated.Member
    public long getAvailableStorageMB() {
        return mAvailableStorageMB;
    }

    /**
     * Battery percentage.
     */
    @DataClass.Generated.Member
    public int getBatteryPercentage() {
        return mBatteryPercentage;
    }

    /**
     * Carrier. See the full list {@link Carrier}.
     */
    @DataClass.Generated.Member
    public int getCarrier() {
        return mCarrier;
    }

    /**
     * Network connection types. See full list {@link RawUserData.ConnectionType}.
     */
    @DataClass.Generated.Member
    public int getConnectionType() {
        return mConnectionType;
    }

    /**
     * Connection speed in kbps.
     */
    @DataClass.Generated.Member
    public long getNetworkConnectionSpeedKbps() {
        return mNetworkConnectionSpeedKbps;
    }

    /**
     * Status if network is metered. False - not metered. True - metered.
     */
    @DataClass.Generated.Member
    public boolean isNetworkMetered() {
        return mNetworkMetered;
    }

    /**
     * The history of installed/uninstalled packages.
     */
    @DataClass.Generated.Member
    public @NonNull Map<String,AppInstallStatus> getAppInstalledHistory() {
        return mAppInstalledHistory;
    }

    /**
     * The app usage history in the last 30 days, sorted by total time spent.
     */
    @DataClass.Generated.Member
    public @NonNull List<AppUsageStatus> getAppUsageHistory() {
        return mAppUsageHistory;
    }

    /**
     * The most recently known location.
     */
    @DataClass.Generated.Member
    public @NonNull Location getCurrentLocation() {
        return mCurrentLocation;
    }

    /**
     * The location history in last 30 days, sorted by the stay duration.
     */
    @DataClass.Generated.Member
    public @NonNull List<LocationStatus> getLocationHistory() {
        return mLocationHistory;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(UserData other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        UserData that = (UserData) o;
        //noinspection PointlessBooleanExpression
        return true
                && mTimestampSec == that.mTimestampSec
                && mTimezoneUtcOffsetMins == that.mTimezoneUtcOffsetMins
                && mOrientation == that.mOrientation
                && mAvailableStorageMB == that.mAvailableStorageMB
                && mBatteryPercentage == that.mBatteryPercentage
                && mCarrier == that.mCarrier
                && mConnectionType == that.mConnectionType
                && mNetworkConnectionSpeedKbps == that.mNetworkConnectionSpeedKbps
                && mNetworkMetered == that.mNetworkMetered
                && java.util.Objects.equals(mAppInstalledHistory, that.mAppInstalledHistory)
                && java.util.Objects.equals(mAppUsageHistory, that.mAppUsageHistory)
                && java.util.Objects.equals(mCurrentLocation, that.mCurrentLocation)
                && java.util.Objects.equals(mLocationHistory, that.mLocationHistory);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + Long.hashCode(mTimestampSec);
        _hash = 31 * _hash + mTimezoneUtcOffsetMins;
        _hash = 31 * _hash + mOrientation;
        _hash = 31 * _hash + Long.hashCode(mAvailableStorageMB);
        _hash = 31 * _hash + mBatteryPercentage;
        _hash = 31 * _hash + mCarrier;
        _hash = 31 * _hash + mConnectionType;
        _hash = 31 * _hash + Long.hashCode(mNetworkConnectionSpeedKbps);
        _hash = 31 * _hash + Boolean.hashCode(mNetworkMetered);
        _hash = 31 * _hash + java.util.Objects.hashCode(mAppInstalledHistory);
        _hash = 31 * _hash + java.util.Objects.hashCode(mAppUsageHistory);
        _hash = 31 * _hash + java.util.Objects.hashCode(mCurrentLocation);
        _hash = 31 * _hash + java.util.Objects.hashCode(mLocationHistory);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        int flg = 0;
        if (mNetworkMetered) flg |= 0x100;
        dest.writeInt(flg);
        dest.writeLong(mTimestampSec);
        dest.writeInt(mTimezoneUtcOffsetMins);
        dest.writeInt(mOrientation);
        dest.writeLong(mAvailableStorageMB);
        dest.writeInt(mBatteryPercentage);
        dest.writeInt(mCarrier);
        dest.writeInt(mConnectionType);
        dest.writeLong(mNetworkConnectionSpeedKbps);
        dest.writeMap(mAppInstalledHistory);
        dest.writeParcelableList(mAppUsageHistory, flags);
        dest.writeTypedObject(mCurrentLocation, flags);
        dest.writeParcelableList(mLocationHistory, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ UserData(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        int flg = in.readInt();
        boolean networkMetered = (flg & 0x100) != 0;
        long timestampSec = in.readLong();
        int timezoneUtcOffsetMins = in.readInt();
        int orientation = in.readInt();
        long availableStorageMB = in.readLong();
        int batteryPercentage = in.readInt();
        int carrier = in.readInt();
        int connectionType = in.readInt();
        long networkConnectionSpeedKbps = in.readLong();
        Map<String,AppInstallStatus> appInstalledHistory = new java.util.LinkedHashMap<>();
        in.readMap(appInstalledHistory, AppInstallStatus.class.getClassLoader());
        List<AppUsageStatus> appUsageHistory = new java.util.ArrayList<>();
        in.readParcelableList(appUsageHistory, AppUsageStatus.class.getClassLoader());
        Location currentLocation = (Location) in.readTypedObject(Location.CREATOR);
        List<LocationStatus> locationHistory = new java.util.ArrayList<>();
        in.readParcelableList(locationHistory, LocationStatus.class.getClassLoader());

        this.mTimestampSec = timestampSec;
        this.mTimezoneUtcOffsetMins = timezoneUtcOffsetMins;
        this.mOrientation = orientation;
        this.mAvailableStorageMB = availableStorageMB;
        this.mBatteryPercentage = batteryPercentage;
        this.mCarrier = carrier;
        this.mConnectionType = connectionType;
        this.mNetworkConnectionSpeedKbps = networkConnectionSpeedKbps;
        this.mNetworkMetered = networkMetered;
        this.mAppInstalledHistory = appInstalledHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mAppInstalledHistory);
        this.mAppUsageHistory = appUsageHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mAppUsageHistory);
        this.mCurrentLocation = currentLocation;
        AnnotationValidations.validate(
                NonNull.class, null, mCurrentLocation);
        this.mLocationHistory = locationHistory;
        AnnotationValidations.validate(
                NonNull.class, null, mLocationHistory);

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<UserData> CREATOR
            = new Parcelable.Creator<UserData>() {
        @Override
        public UserData[] newArray(int size) {
            return new UserData[size];
        }

        @Override
        public UserData createFromParcel(@NonNull android.os.Parcel in) {
            return new UserData(in);
        }
    };

    /**
     * A builder for {@link UserData}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private long mTimestampSec;
        private int mTimezoneUtcOffsetMins;
        private int mOrientation;
        private long mAvailableStorageMB;
        private int mBatteryPercentage;
        private int mCarrier;
        private int mConnectionType;
        private long mNetworkConnectionSpeedKbps;
        private boolean mNetworkMetered;
        private @NonNull Map<String,AppInstallStatus> mAppInstalledHistory;
        private @NonNull List<AppUsageStatus> mAppUsageHistory;
        private @NonNull Location mCurrentLocation;
        private @NonNull List<LocationStatus> mLocationHistory;

        private long mBuilderFieldsSet = 0L;

        /**
         * Creates a new Builder.
         *
         * @param timestampSec
         *   The current timestamp in second.
         * @param timezoneUtcOffsetMins
         *   The device timezone +/- minutes offset from UTC.
         * @param orientation
         *   The device orientation.
         * @param availableStorageMB
         *   The available space on device in MB.
         * @param batteryPercentage
         *   Battery percentage.
         * @param carrier
         *   Carrier. See the full list {@link Carrier}.
         * @param connectionType
         *   Network connection types. See full list {@link RawUserData.ConnectionType}.
         * @param networkConnectionSpeedKbps
         *   Connection speed in kbps.
         * @param networkMetered
         *   Status if network is metered. False - not metered. True - metered.
         * @param appInstalledHistory
         *   The history of installed/uninstalled packages.
         * @param appUsageHistory
         *   The app usage history in the last 30 days, sorted by total time spent.
         * @param currentLocation
         *   The most recently known location.
         * @param locationHistory
         *   The location history in last 30 days, sorted by the stay duration.
         */
        public Builder(
                long timestampSec,
                int timezoneUtcOffsetMins,
                int orientation,
                long availableStorageMB,
                int batteryPercentage,
                int carrier,
                int connectionType,
                long networkConnectionSpeedKbps,
                boolean networkMetered,
                @NonNull Map<String,AppInstallStatus> appInstalledHistory,
                @NonNull List<AppUsageStatus> appUsageHistory,
                @NonNull Location currentLocation,
                @NonNull List<LocationStatus> locationHistory) {
            mTimestampSec = timestampSec;
            mTimezoneUtcOffsetMins = timezoneUtcOffsetMins;
            mOrientation = orientation;
            mAvailableStorageMB = availableStorageMB;
            mBatteryPercentage = batteryPercentage;
            mCarrier = carrier;
            mConnectionType = connectionType;
            mNetworkConnectionSpeedKbps = networkConnectionSpeedKbps;
            mNetworkMetered = networkMetered;
            mAppInstalledHistory = appInstalledHistory;
            AnnotationValidations.validate(
                    NonNull.class, null, mAppInstalledHistory);
            mAppUsageHistory = appUsageHistory;
            AnnotationValidations.validate(
                    NonNull.class, null, mAppUsageHistory);
            mCurrentLocation = currentLocation;
            AnnotationValidations.validate(
                    NonNull.class, null, mCurrentLocation);
            mLocationHistory = locationHistory;
            AnnotationValidations.validate(
                    NonNull.class, null, mLocationHistory);
        }

        public Builder() {
        }

        /**
         * The current timestamp in second.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setTimestampSec(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mTimestampSec = value;
            return this;
        }

        /**
         * The device timezone +/- minutes offset from UTC.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setTimezoneUtcOffsetMins(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mTimezoneUtcOffsetMins = value;
            return this;
        }

        /**
         * The device orientation.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setOrientation(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mOrientation = value;
            return this;
        }

        /**
         * The available space on device in MB.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setAvailableStorageMB(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8;
            mAvailableStorageMB = value;
            return this;
        }

        /**
         * Battery percentage.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setBatteryPercentage(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x10;
            mBatteryPercentage = value;
            return this;
        }

        /**
         * Carrier. See the full list {@link Carrier}.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setCarrier(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x20;
            mCarrier = value;
            return this;
        }

        /**
         * Network connection types. See full list {@link RawUserData.ConnectionType}.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setConnectionType(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x40;
            mConnectionType = value;
            return this;
        }

        /**
         * Connection speed in kbps.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setNetworkConnectionSpeedKbps(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x80;
            mNetworkConnectionSpeedKbps = value;
            return this;
        }

        /**
         * Status if network is metered. False - not metered. True - metered.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setNetworkMetered(boolean value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x100;
            mNetworkMetered = value;
            return this;
        }

        /**
         * The history of installed/uninstalled packages.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setAppInstalledHistory(@NonNull Map<String,AppInstallStatus> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x200;
            mAppInstalledHistory = value;
            return this;
        }

        /** @see #setAppInstalledHistory */
        @DataClass.Generated.Member
        public @NonNull Builder addAppInstalledHistory(@NonNull String key, @NonNull AppInstallStatus value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mAppInstalledHistory == null) setAppInstalledHistory(new java.util.LinkedHashMap());
            mAppInstalledHistory.put(key, value);
            return this;
        }

        /**
         * The app usage history in the last 30 days, sorted by total time spent.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setAppUsageHistory(@NonNull List<AppUsageStatus> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x400;
            mAppUsageHistory = value;
            return this;
        }

        /** @see #setAppUsageHistory */
        @DataClass.Generated.Member
        public @NonNull Builder addAppUsageHistory(@NonNull AppUsageStatus value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mAppUsageHistory == null) setAppUsageHistory(new java.util.ArrayList<>());
            mAppUsageHistory.add(value);
            return this;
        }

        /**
         * The most recently known location.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setCurrentLocation(@NonNull Location value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x800;
            mCurrentLocation = value;
            return this;
        }

        /**
         * The location history in last 30 days, sorted by the stay duration.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setLocationHistory(@NonNull List<LocationStatus> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1000;
            mLocationHistory = value;
            return this;
        }

        /** @see #setLocationHistory */
        @DataClass.Generated.Member
        public @NonNull Builder addLocationHistory(@NonNull LocationStatus value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mLocationHistory == null) setLocationHistory(new java.util.ArrayList<>());
            mLocationHistory.add(value);
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull UserData build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2000; // Mark builder used

            UserData o = new UserData(
                    mTimestampSec,
                    mTimezoneUtcOffsetMins,
                    mOrientation,
                    mAvailableStorageMB,
                    mBatteryPercentage,
                    mCarrier,
                    mConnectionType,
                    mNetworkConnectionSpeedKbps,
                    mNetworkMetered,
                    mAppInstalledHistory,
                    mAppUsageHistory,
                    mCurrentLocation,
                    mLocationHistory);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x2000) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1687391241307L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/UserData.java",
            inputSignatures = "  long mTimestampSec\n  int mTimezoneUtcOffsetMins\n  int mOrientation\n  long mAvailableStorageMB\n  int mBatteryPercentage\n  int mCarrier\n  int mConnectionType\n  long mNetworkConnectionSpeedKbps\n  boolean mNetworkMetered\n @android.annotation.NonNull java.util.Map<java.lang.String,android.ondevicepersonalization.AppInstallStatus> mAppInstalledHistory\n @android.annotation.NonNull java.util.List<android.ondevicepersonalization.AppUsageStatus> mAppUsageHistory\n @android.annotation.NonNull android.ondevicepersonalization.Location mCurrentLocation\n @android.annotation.NonNull java.util.List<android.ondevicepersonalization.LocationStatus> mLocationHistory\nclass UserData extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
