/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.ondevicepersonalization.services.data.events;

import android.annotation.NonNull;
import android.annotation.Nullable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * Query object for the Query table
 */
@DataClass(
        genBuilder = true,
        genEqualsHashCode = true
)
public class Query {
    /** The id of the query. */
    @Nullable
    private final long mQueryId;

    /** Time of the query in milliseconds. */
    @NonNull
    private final long mTimeMillis;

    /** Blob representing the query. */
    @NonNull
    private final byte[] mQuery;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/src/com/android/ondevicepersonalization/services/data/events/Query.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ Query(
            @Nullable long queryId,
            @NonNull long timeMillis,
            @NonNull byte[] query) {
        this.mQueryId = queryId;
        this.mTimeMillis = timeMillis;
        AnnotationValidations.validate(
                NonNull.class, null, mTimeMillis);
        this.mQuery = query;
        AnnotationValidations.validate(
                NonNull.class, null, mQuery);

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * The id of the query.
     */
    @DataClass.Generated.Member
    public @Nullable long getQueryId() {
        return mQueryId;
    }

    /**
     * Time of the query in milliseconds.
     */
    @DataClass.Generated.Member
    public @NonNull long getTimeMillis() {
        return mTimeMillis;
    }

    /**
     * Blob representing the query.
     */
    @DataClass.Generated.Member
    public @NonNull byte[] getQuery() {
        return mQuery;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(Query other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        Query that = (Query) o;
        //noinspection PointlessBooleanExpression
        return true
                && mQueryId == that.mQueryId
                && mTimeMillis == that.mTimeMillis
                && java.util.Arrays.equals(mQuery, that.mQuery);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + Long.hashCode(mQueryId);
        _hash = 31 * _hash + Long.hashCode(mTimeMillis);
        _hash = 31 * _hash + java.util.Arrays.hashCode(mQuery);
        return _hash;
    }

    /**
     * A builder for {@link Query}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static class Builder {

        private @Nullable long mQueryId;
        private @NonNull long mTimeMillis;
        private @NonNull byte[] mQuery;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * Creates a new Builder.
         *
         * @param queryId
         *   The id of the query.
         * @param timeMillis
         *   Time of the query in milliseconds.
         * @param query
         *   Blob representing the query.
         */
        public Builder(
                @Nullable long queryId,
                @NonNull long timeMillis,
                @NonNull byte[] query) {
            mQueryId = queryId;
            mTimeMillis = timeMillis;
            AnnotationValidations.validate(
                    NonNull.class, null, mTimeMillis);
            mQuery = query;
            AnnotationValidations.validate(
                    NonNull.class, null, mQuery);
        }

        /**
         * The id of the query.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setQueryId(@NonNull long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mQueryId = value;
            return this;
        }

        /**
         * Time of the query in milliseconds.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setTimeMillis(@NonNull long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mTimeMillis = value;
            return this;
        }

        /**
         * Blob representing the query.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setQuery(@NonNull byte... value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mQuery = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull Query build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            Query o = new Query(
                    mQueryId,
                    mTimeMillis,
                    mQuery);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1674839300496L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/src/com/android/ondevicepersonalization/services/data/events/Query.java",
            inputSignatures = "private final @android.annotation.Nullable long mQueryId\nprivate final @android.annotation.NonNull long mTimeMillis\nprivate final @android.annotation.NonNull byte[] mQuery\nclass Query extends java.lang.Object implements []\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
