/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.ondevicepersonalization.rtb;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.os.Parcelable;
import android.os.PersistableBundle;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.List;

/**
 * A SeatBid object returned within a {@link BidResponse}.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class SeatBid implements Parcelable {
    /** A list of {@link Bid} objects. */
    @Nullable private List<Bid> mBids = null;

    /** Id of the buyer (advertiser, agency etc) seat on behalf of whom this bid is made. */
    @NonNull private String mSeat = "";

    /** Custom data returned by bidder to exchange for filtering. Not logged. */
    @Nullable private PersistableBundle mExt = null;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen Banner.java Bid.java BidRequest.java BidResponse.java Imp.java $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/rtb/SeatBid.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ SeatBid(
            @Nullable List<Bid> bids,
            @NonNull String seat,
            @Nullable PersistableBundle ext) {
        this.mBids = bids;
        this.mSeat = seat;
        AnnotationValidations.validate(
                NonNull.class, null, mSeat);
        this.mExt = ext;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * A list of {@link Bid} objects.
     */
    @DataClass.Generated.Member
    public @Nullable List<Bid> getBids() {
        return mBids;
    }

    /**
     * Id of the buyer (advertiser, agency etc) seat on behalf of whom this bid is made.
     */
    @DataClass.Generated.Member
    public @NonNull String getSeat() {
        return mSeat;
    }

    /**
     * Custom data returned by bidder to exchange for filtering. Not logged.
     */
    @DataClass.Generated.Member
    public @Nullable PersistableBundle getExt() {
        return mExt;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(SeatBid other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        SeatBid that = (SeatBid) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mBids, that.mBids)
                && java.util.Objects.equals(mSeat, that.mSeat)
                && java.util.Objects.equals(mExt, that.mExt);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mBids);
        _hash = 31 * _hash + java.util.Objects.hashCode(mSeat);
        _hash = 31 * _hash + java.util.Objects.hashCode(mExt);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mBids != null) flg |= 0x1;
        if (mExt != null) flg |= 0x4;
        dest.writeByte(flg);
        if (mBids != null) dest.writeParcelableList(mBids, flags);
        dest.writeString(mSeat);
        if (mExt != null) dest.writeTypedObject(mExt, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ SeatBid(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        List<Bid> bids = null;
        if ((flg & 0x1) != 0) {
            bids = new java.util.ArrayList<>();
            in.readParcelableList(bids, Bid.class.getClassLoader());
        }
        String seat = in.readString();
        PersistableBundle ext = (flg & 0x4) == 0 ? null : (PersistableBundle) in.readTypedObject(PersistableBundle.CREATOR);

        this.mBids = bids;
        this.mSeat = seat;
        AnnotationValidations.validate(
                NonNull.class, null, mSeat);
        this.mExt = ext;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<SeatBid> CREATOR
            = new Parcelable.Creator<SeatBid>() {
        @Override
        public SeatBid[] newArray(int size) {
            return new SeatBid[size];
        }

        @Override
        public SeatBid createFromParcel(@NonNull android.os.Parcel in) {
            return new SeatBid(in);
        }
    };

    /**
     * A builder for {@link SeatBid}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @Nullable List<Bid> mBids;
        private @NonNull String mSeat;
        private @Nullable PersistableBundle mExt;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * A list of {@link Bid} objects.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setBids(@NonNull List<Bid> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mBids = value;
            return this;
        }

        /** @see #setBids */
        @DataClass.Generated.Member
        public @NonNull Builder addBids(@NonNull Bid value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mBids == null) setBids(new java.util.ArrayList<>());
            mBids.add(value);
            return this;
        }

        /**
         * Id of the buyer (advertiser, agency etc) seat on behalf of whom this bid is made.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setSeat(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mSeat = value;
            return this;
        }

        /**
         * Custom data returned by bidder to exchange for filtering. Not logged.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setExt(@NonNull PersistableBundle value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mExt = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull SeatBid build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mBids = null;
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mSeat = "";
            }
            if ((mBuilderFieldsSet & 0x4) == 0) {
                mExt = null;
            }
            SeatBid o = new SeatBid(
                    mBids,
                    mSeat,
                    mExt);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1659465221623L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/rtb/SeatBid.java",
            inputSignatures = "private @android.annotation.Nullable java.util.List<android.ondevicepersonalization.rtb.Bid> mBids\nprivate @android.annotation.NonNull java.lang.String mSeat\nprivate @android.annotation.Nullable android.os.PersistableBundle mExt\nclass SeatBid extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
