/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.adservices.ondevicepersonalization;

import android.annotation.Nullable;

import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.function.Consumer;

/**
 * The output data of {@link IsolatedWorker#onTrainingExample(ExampleInput, Consumer)}
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public class ExampleOutput {
    /**
     * Returns null if input data is not going be used for federated computation. For example, if
     * client plans to train a spanish language model and input data is english text, the expect
     * output is null.
     *
     * <p>Returns a single training example byte array if input data is used. The format is binary
     * seriazlied tf.Example proto by default. The maximum example size is 50KB to avoid hitting
     * Binder IPC size limit.
     */
    @Nullable private byte[] mTrainingExample = null;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen
    // $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/ExampleOutput.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ ExampleOutput(@Nullable byte[] trainingExample) {
        this.mTrainingExample = trainingExample;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * Returns null if input data is not going be used for federated computation. For example, if
     * client plans to train a spanish language model and input data is english text, the expect
     * output is null.
     *
     * <p>Returns a single training example byte array if input data is used. The format is binary
     * seriazlied tf.Example proto by default. The maximum example size is 50KB to avoid hitting
     * Binder IPC size limit.
     */
    @DataClass.Generated.Member
    public @Nullable byte[] getTrainingExample() {
        return mTrainingExample;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(ExampleOutput other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        ExampleOutput that = (ExampleOutput) o;
        //noinspection PointlessBooleanExpression
        return true && java.util.Arrays.equals(mTrainingExample, that.mTrainingExample);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Arrays.hashCode(mTrainingExample);
        return _hash;
    }

    /** A builder for {@link ExampleOutput} */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @Nullable byte[] mTrainingExample;

        private long mBuilderFieldsSet = 0L;

        public Builder() {}

        /**
         * Returns null if input data is not going be used for federated computation. For example,
         * if client plans to train a spanish language model and input data is english text, the
         * expect output is null.
         *
         * <p>Returns a single training example byte array if input data is used. The format is
         * binary seriazlied tf.Example proto by default. The maximum example size is 50KB to avoid
         * hitting Binder IPC size limit.
         */
        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setTrainingExample(
                @android.annotation.NonNull byte... value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mTrainingExample = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull ExampleOutput build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mTrainingExample = null;
            }
            ExampleOutput o = new ExampleOutput(mTrainingExample);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x2) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1694819864484L,
            codegenVersion = "1.0.23",
            sourceFile =
                    "packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/ExampleOutput.java",
            inputSignatures =
                    "private final @android.annotation.Nullable byte[] mTrainingExample\nclass ExampleOutput extends java.lang.Object implements []\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}

    // @formatter:on
    // End of generated code

}
