/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.adservices.ondevicepersonalization;

import android.annotation.NonNull;
import android.content.ContentValues;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.Collections;
import java.util.List;

/**
 * Contains data that will be written to the REQUESTS table at the end of a call to
 * {@link IsolatedWorker#onExecute()}.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class RequestLogRecord implements Parcelable {
    /**
     * A List of rows, each containing a {@link ContentValues}.
     **/
    @DataClass.PluralOf("row")
    @NonNull List<ContentValues> mRows = Collections.emptyList();



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/RequestLogRecord.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ RequestLogRecord(
            @NonNull List<ContentValues> rows) {
        this.mRows = rows;
        AnnotationValidations.validate(
                NonNull.class, null, mRows);

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * A List of rows, each containing a {@link ContentValues}.
     */
    @DataClass.Generated.Member
    public @NonNull List<ContentValues> getRows() {
        return mRows;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(RequestLogRecord other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        RequestLogRecord that = (RequestLogRecord) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mRows, that.mRows);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mRows);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        dest.writeParcelableList(mRows, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ RequestLogRecord(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        List<ContentValues> rows = new java.util.ArrayList<>();
        in.readParcelableList(rows, ContentValues.class.getClassLoader());

        this.mRows = rows;
        AnnotationValidations.validate(
                NonNull.class, null, mRows);

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<RequestLogRecord> CREATOR
            = new Parcelable.Creator<RequestLogRecord>() {
        @Override
        public RequestLogRecord[] newArray(int size) {
            return new RequestLogRecord[size];
        }

        @Override
        public RequestLogRecord createFromParcel(@NonNull android.os.Parcel in) {
            return new RequestLogRecord(in);
        }
    };

    /**
     * A builder for {@link RequestLogRecord}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull List<ContentValues> mRows;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * A List of rows, each containing a {@link ContentValues}.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setRows(@NonNull List<ContentValues> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mRows = value;
            return this;
        }

        /** @see #setRows */
        @DataClass.Generated.Member
        public @NonNull Builder addRow(@NonNull ContentValues value) {
            if (mRows == null) setRows(new java.util.ArrayList<>());
            mRows.add(value);
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull RequestLogRecord build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mRows = Collections.emptyList();
            }
            RequestLogRecord o = new RequestLogRecord(
                    mRows);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x2) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1692118422731L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/adservices/ondevicepersonalization/RequestLogRecord.java",
            inputSignatures = " @com.android.ondevicepersonalization.internal.util.DataClass.PluralOf(\"row\") @android.annotation.NonNull java.util.List<android.content.ContentValues> mRows\nclass RequestLogRecord extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
