/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.federatedcompute.services.common;

import com.android.ondevicepersonalization.internal.util.DataClass;

/** The collections of examples usage statistics. */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public class ExampleStats {
    private int mExampleCount = 0;
    private long mExampleSizeBytes = 0;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/federatedcompute/src
    // /com/android/federatedcompute/services/common/ExampleStats.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ ExampleStats(int exampleCount, long exampleSizeBytes) {
        this.mExampleCount = exampleCount;
        this.mExampleSizeBytes = exampleSizeBytes;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public int getExampleCount() {
        return mExampleCount;
    }

    @DataClass.Generated.Member
    public long getExampleSizeBytes() {
        return mExampleSizeBytes;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(ExampleStats other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        ExampleStats that = (ExampleStats) o;
        //noinspection PointlessBooleanExpression
        return true
                && mExampleCount == that.mExampleCount
                && mExampleSizeBytes == that.mExampleSizeBytes;
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + mExampleCount;
        _hash = 31 * _hash + Long.hashCode(mExampleSizeBytes);
        return _hash;
    }

    /** A builder for {@link ExampleStats} */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static class Builder {

        private int mExampleCount;
        private long mExampleSizeBytes;

        private long mBuilderFieldsSet = 0L;

        public Builder() {}

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleCount(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mExampleCount = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleSizeBytes(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mExampleSizeBytes = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull ExampleStats build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mExampleCount = 0;
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mExampleSizeBytes = 0;
            }
            ExampleStats o = new ExampleStats(mExampleCount, mExampleSizeBytes);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x4) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1704316294704L,
            codegenVersion = "1.0.23",
            sourceFile =
                    "packages/modules/OnDevicePersonalization/federatedcompute/src/com/android/federatedcompute/services/common/ExampleStats.java",
            inputSignatures =
                    "private  int mExampleCount\n"
                        + "private  long mExampleSizeBytes\n"
                        + "class ExampleStats extends java.lang.Object implements []\n"
                        + "@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true,"
                        + " genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}

    // @formatter:on
    // End of generated code

}
