/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.ondevicepersonalization;

import android.annotation.NonNull;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * The result returned by an exchange in response to a request from a calling app.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class ExchangeResult implements Parcelable {
    /**
     * The reporting id for this response. Must be a key in the VendorData table for this exchange.
     */
    @NonNull private String mKey = "";

    /**
     * The HTML snippet to be rendered in a WebView.
     */
    @NonNull private String mResponse = "";

    // TODO(b/19460933): Add other fields that need to be logged.


    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/ExchangeResult.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ ExchangeResult(
            @NonNull String key,
            @NonNull String response) {
        this.mKey = key;
        AnnotationValidations.validate(
                NonNull.class, null, mKey);
        this.mResponse = response;
        AnnotationValidations.validate(
                NonNull.class, null, mResponse);

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * The reporting id for this response. Must be a key in the VendorData table for this exchange.
     */
    @DataClass.Generated.Member
    public @NonNull String getKey() {
        return mKey;
    }

    /**
     * The HTML snippet to be rendered in a WebView.
     */
    @DataClass.Generated.Member
    public @NonNull String getResponse() {
        return mResponse;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(ExchangeResult other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        ExchangeResult that = (ExchangeResult) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mKey, that.mKey)
                && java.util.Objects.equals(mResponse, that.mResponse);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mKey);
        _hash = 31 * _hash + java.util.Objects.hashCode(mResponse);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        dest.writeString(mKey);
        dest.writeString(mResponse);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ ExchangeResult(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        String key = in.readString();
        String response = in.readString();

        this.mKey = key;
        AnnotationValidations.validate(
                NonNull.class, null, mKey);
        this.mResponse = response;
        AnnotationValidations.validate(
                NonNull.class, null, mResponse);

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<ExchangeResult> CREATOR
            = new Parcelable.Creator<ExchangeResult>() {
        @Override
        public ExchangeResult[] newArray(int size) {
            return new ExchangeResult[size];
        }

        @Override
        public ExchangeResult createFromParcel(@NonNull android.os.Parcel in) {
            return new ExchangeResult(in);
        }
    };

    /**
     * A builder for {@link ExchangeResult}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull String mKey;
        private @NonNull String mResponse;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * The reporting id for this response. Must be a key in the VendorData table for this exchange.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setKey(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mKey = value;
            return this;
        }

        /**
         * The HTML snippet to be rendered in a WebView.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setResponse(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mResponse = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull ExchangeResult build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mKey = "";
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mResponse = "";
            }
            ExchangeResult o = new ExchangeResult(
                    mKey,
                    mResponse);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x4) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1659379661450L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/ExchangeResult.java",
            inputSignatures = "private @android.annotation.NonNull java.lang.String mKey\nprivate @android.annotation.NonNull java.lang.String mResponse\nclass ExchangeResult extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
