/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.ondevicepersonalization;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.os.Parcelable;
import android.os.PersistableBundle;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.List;

/**
 * The output to be rendered in a slot within a calling app.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class SelectContentInput implements Parcelable {
    /** The package name of the calling app. */
    @NonNull String mAppPackageName;

    /** Properties of each slot within the calling app where content is to be rendered. */
    @NonNull private List<SlotInfo> mSlotInfos;

    /** Parameters provided by the app to the {@link PersonalizationService}. */
    @Nullable PersistableBundle mAppParams;



    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SelectContentInput.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ SelectContentInput(
            @NonNull String appPackageName,
            @NonNull List<SlotInfo> slotInfos,
            @Nullable PersistableBundle appParams) {
        this.mAppPackageName = appPackageName;
        AnnotationValidations.validate(
                NonNull.class, null, mAppPackageName);
        this.mSlotInfos = slotInfos;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotInfos);
        this.mAppParams = appParams;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * The package name of the calling app.
     */
    @DataClass.Generated.Member
    public @NonNull String getAppPackageName() {
        return mAppPackageName;
    }

    /**
     * Properties of each slot within the calling app where content is to be rendered.
     */
    @DataClass.Generated.Member
    public @NonNull List<SlotInfo> getSlotInfos() {
        return mSlotInfos;
    }

    /**
     * Parameters provided by the app to the {@link PersonalizationService}.
     */
    @DataClass.Generated.Member
    public @Nullable PersistableBundle getAppParams() {
        return mAppParams;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(SelectContentInput other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        SelectContentInput that = (SelectContentInput) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mAppPackageName, that.mAppPackageName)
                && java.util.Objects.equals(mSlotInfos, that.mSlotInfos)
                && java.util.Objects.equals(mAppParams, that.mAppParams);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mAppPackageName);
        _hash = 31 * _hash + java.util.Objects.hashCode(mSlotInfos);
        _hash = 31 * _hash + java.util.Objects.hashCode(mAppParams);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mAppParams != null) flg |= 0x4;
        dest.writeByte(flg);
        dest.writeString(mAppPackageName);
        dest.writeParcelableList(mSlotInfos, flags);
        if (mAppParams != null) dest.writeTypedObject(mAppParams, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ SelectContentInput(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        String appPackageName = in.readString();
        List<SlotInfo> slotInfos = new java.util.ArrayList<>();
        in.readParcelableList(slotInfos, SlotInfo.class.getClassLoader());
        PersistableBundle appParams = (flg & 0x4) == 0 ? null : (PersistableBundle) in.readTypedObject(PersistableBundle.CREATOR);

        this.mAppPackageName = appPackageName;
        AnnotationValidations.validate(
                NonNull.class, null, mAppPackageName);
        this.mSlotInfos = slotInfos;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotInfos);
        this.mAppParams = appParams;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<SelectContentInput> CREATOR
            = new Parcelable.Creator<SelectContentInput>() {
        @Override
        public SelectContentInput[] newArray(int size) {
            return new SelectContentInput[size];
        }

        @Override
        public SelectContentInput createFromParcel(@NonNull android.os.Parcel in) {
            return new SelectContentInput(in);
        }
    };

    /**
     * A builder for {@link SelectContentInput}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull String mAppPackageName;
        private @NonNull List<SlotInfo> mSlotInfos;
        private @Nullable PersistableBundle mAppParams;

        private long mBuilderFieldsSet = 0L;

        /**
         * Creates a new Builder.
         */
        public Builder() {
        }

        /**
         * The package name of the calling app.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setAppPackageName(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mAppPackageName = value;
            return this;
        }

        /**
         * Properties of each slot within the calling app where content is to be rendered.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setSlotInfos(@NonNull List<SlotInfo> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mSlotInfos = value;
            return this;
        }

        /** @see #setSlotInfos */
        @DataClass.Generated.Member
        public @NonNull Builder addSlotInfos(@NonNull SlotInfo value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mSlotInfos == null) setSlotInfos(new java.util.ArrayList<>());
            mSlotInfos.add(value);
            return this;
        }

        /**
         * Parameters provided by the app to the {@link PersonalizationService}.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setAppParams(@NonNull PersistableBundle value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mAppParams = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull SelectContentInput build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            SelectContentInput o = new SelectContentInput(
                    mAppPackageName,
                    mSlotInfos,
                    mAppParams);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1675280235088L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SelectContentInput.java",
            inputSignatures = " @android.annotation.NonNull java.lang.String mAppPackageName\nprivate @android.annotation.NonNull android.ondevicepersonalization.List<android.ondevicepersonalization.SlotInfo> mSlotInfos\n @android.annotation.Nullable android.os.PersistableBundle mAppParams\nclass SelectContentInput extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
