/*
 * Copyright (C) 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package android.ondevicepersonalization;

import android.annotation.NonNull;
import android.annotation.Nullable;
import android.os.Parcelable;

import com.android.ondevicepersonalization.internal.util.AnnotationValidations;
import com.android.ondevicepersonalization.internal.util.DataClass;

import java.util.List;

/**
 * The result for one of the slots in the request from a calling app.
 *
 * @hide
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public final class SlotResult implements Parcelable {
    /**
     * A key in the REMOTE_DATA table that identifies this slot.
     */
    @NonNull private String mSlotId = "";

    /**
     * A list of winning bids in this slot. Will be rendered and logged for
     * reporting and training.
     */
    @Nullable private List<Bid> mWinningBids = null;

    /**
     * A list of candidate bids that were rejected. Will be logged for training.
     */
    @Nullable private List<Bid> mRejectedBids = null;




    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SlotResult.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    //@formatter:off


    @DataClass.Generated.Member
    /* package-private */ SlotResult(
            @NonNull String slotId,
            @Nullable List<Bid> winningBids,
            @Nullable List<Bid> rejectedBids) {
        this.mSlotId = slotId;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotId);
        this.mWinningBids = winningBids;
        this.mRejectedBids = rejectedBids;

        // onConstructed(); // You can define this method to get a callback
    }

    /**
     * A key in the REMOTE_DATA table that identifies this slot.
     */
    @DataClass.Generated.Member
    public @NonNull String getSlotId() {
        return mSlotId;
    }

    /**
     * A list of winning bids in this slot. Will be rendered and logged for
     * reporting and training.
     */
    @DataClass.Generated.Member
    public @Nullable List<Bid> getWinningBids() {
        return mWinningBids;
    }

    /**
     * A list of candidate bids that were rejected. Will be logged for training.
     */
    @DataClass.Generated.Member
    public @Nullable List<Bid> getRejectedBids() {
        return mRejectedBids;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(SlotResult other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        SlotResult that = (SlotResult) o;
        //noinspection PointlessBooleanExpression
        return true
                && java.util.Objects.equals(mSlotId, that.mSlotId)
                && java.util.Objects.equals(mWinningBids, that.mWinningBids)
                && java.util.Objects.equals(mRejectedBids, that.mRejectedBids);
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + java.util.Objects.hashCode(mSlotId);
        _hash = 31 * _hash + java.util.Objects.hashCode(mWinningBids);
        _hash = 31 * _hash + java.util.Objects.hashCode(mRejectedBids);
        return _hash;
    }

    @Override
    @DataClass.Generated.Member
    public void writeToParcel(@NonNull android.os.Parcel dest, int flags) {
        // You can override field parcelling by defining methods like:
        // void parcelFieldName(Parcel dest, int flags) { ... }

        byte flg = 0;
        if (mWinningBids != null) flg |= 0x2;
        if (mRejectedBids != null) flg |= 0x4;
        dest.writeByte(flg);
        dest.writeString(mSlotId);
        if (mWinningBids != null) dest.writeParcelableList(mWinningBids, flags);
        if (mRejectedBids != null) dest.writeParcelableList(mRejectedBids, flags);
    }

    @Override
    @DataClass.Generated.Member
    public int describeContents() { return 0; }

    /** @hide */
    @SuppressWarnings({"unchecked", "RedundantCast"})
    @DataClass.Generated.Member
    /* package-private */ SlotResult(@NonNull android.os.Parcel in) {
        // You can override field unparcelling by defining methods like:
        // static FieldType unparcelFieldName(Parcel in) { ... }

        byte flg = in.readByte();
        String slotId = in.readString();
        List<Bid> winningBids = null;
        if ((flg & 0x2) != 0) {
            winningBids = new java.util.ArrayList<>();
            in.readParcelableList(winningBids, Bid.class.getClassLoader());
        }
        List<Bid> rejectedBids = null;
        if ((flg & 0x4) != 0) {
            rejectedBids = new java.util.ArrayList<>();
            in.readParcelableList(rejectedBids, Bid.class.getClassLoader());
        }

        this.mSlotId = slotId;
        AnnotationValidations.validate(
                NonNull.class, null, mSlotId);
        this.mWinningBids = winningBids;
        this.mRejectedBids = rejectedBids;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public static final @NonNull Parcelable.Creator<SlotResult> CREATOR
            = new Parcelable.Creator<SlotResult>() {
        @Override
        public SlotResult[] newArray(int size) {
            return new SlotResult[size];
        }

        @Override
        public SlotResult createFromParcel(@NonNull android.os.Parcel in) {
            return new SlotResult(in);
        }
    };

    /**
     * A builder for {@link SlotResult}
     */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static final class Builder {

        private @NonNull String mSlotId;
        private @Nullable List<Bid> mWinningBids;
        private @Nullable List<Bid> mRejectedBids;

        private long mBuilderFieldsSet = 0L;

        public Builder() {
        }

        /**
         * A key in the REMOTE_DATA table that identifies this slot.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setSlotId(@NonNull String value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mSlotId = value;
            return this;
        }

        /**
         * A list of winning bids in this slot. Will be rendered and logged for
         * reporting and training.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setWinningBids(@NonNull List<Bid> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mWinningBids = value;
            return this;
        }

        /** @see #setWinningBids */
        @DataClass.Generated.Member
        public @NonNull Builder addWinningBids(@NonNull Bid value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mWinningBids == null) setWinningBids(new java.util.ArrayList<>());
            mWinningBids.add(value);
            return this;
        }

        /**
         * A list of candidate bids that were rejected. Will be logged for training.
         */
        @DataClass.Generated.Member
        public @NonNull Builder setRejectedBids(@NonNull List<Bid> value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mRejectedBids = value;
            return this;
        }

        /** @see #setRejectedBids */
        @DataClass.Generated.Member
        public @NonNull Builder addRejectedBids(@NonNull Bid value) {
            // You can refine this method's name by providing item's singular name, e.g.:
            // @DataClass.PluralOf("item")) mItems = ...

            if (mRejectedBids == null) setRejectedBids(new java.util.ArrayList<>());
            mRejectedBids.add(value);
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @NonNull SlotResult build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8; // Mark builder used

            if ((mBuilderFieldsSet & 0x1) == 0) {
                mSlotId = "";
            }
            if ((mBuilderFieldsSet & 0x2) == 0) {
                mWinningBids = null;
            }
            if ((mBuilderFieldsSet & 0x4) == 0) {
                mRejectedBids = null;
            }
            SlotResult o = new SlotResult(
                    mSlotId,
                    mWinningBids,
                    mRejectedBids);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x8) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1671484302594L,
            codegenVersion = "1.0.23",
            sourceFile = "packages/modules/OnDevicePersonalization/framework/java/android/ondevicepersonalization/SlotResult.java",
            inputSignatures = "private @android.annotation.NonNull java.lang.String mSlotId\nprivate @android.annotation.Nullable java.util.List<android.ondevicepersonalization.Bid> mWinningBids\nprivate @android.annotation.Nullable java.util.List<android.ondevicepersonalization.Bid> mRejectedBids\nclass SlotResult extends java.lang.Object implements [android.os.Parcelable]\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}


    //@formatter:on
    // End of generated code

}
