/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.federatedcompute.services.statsd;

import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * Class holds FederatedComputeTrainingEventReported defined at
 * frameworks/proto_logging/stats/atoms/federatedcompute/federatedcompute_extension_atoms.proto
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public class TrainingEventReported {
    private long mClientVersion;
    private int mEventKind;
    private long mTaskId;
    private long mDurationInMillis;
    private long mExampleSize = 0;
    private long mDataTransferDurationMillis = 0;
    private long mBytesUploaded = 0;
    private long mBytesDownloaded = 0;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen
    // $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/federatedcompute/src/com/android/federatedcompute/services/statsd/TrainingEventReported.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ TrainingEventReported(
            long clientVersion,
            int eventKind,
            long taskId,
            long durationInMillis,
            long exampleSize,
            long dataTransferDurationMillis,
            long bytesUploaded,
            long bytesDownloaded) {
        this.mClientVersion = clientVersion;
        this.mEventKind = eventKind;
        this.mTaskId = taskId;
        this.mDurationInMillis = durationInMillis;
        this.mExampleSize = exampleSize;
        this.mDataTransferDurationMillis = dataTransferDurationMillis;
        this.mBytesUploaded = bytesUploaded;
        this.mBytesDownloaded = bytesDownloaded;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public long getClientVersion() {
        return mClientVersion;
    }

    @DataClass.Generated.Member
    public int getEventKind() {
        return mEventKind;
    }

    @DataClass.Generated.Member
    public long getTaskId() {
        return mTaskId;
    }

    @DataClass.Generated.Member
    public long getDurationInMillis() {
        return mDurationInMillis;
    }

    @DataClass.Generated.Member
    public long getExampleSize() {
        return mExampleSize;
    }

    @DataClass.Generated.Member
    public long getDataTransferDurationMillis() {
        return mDataTransferDurationMillis;
    }

    @DataClass.Generated.Member
    public long getBytesUploaded() {
        return mBytesUploaded;
    }

    @DataClass.Generated.Member
    public long getBytesDownloaded() {
        return mBytesDownloaded;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(TrainingEventReported other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        TrainingEventReported that = (TrainingEventReported) o;
        //noinspection PointlessBooleanExpression
        return true
                && mClientVersion == that.mClientVersion
                && mEventKind == that.mEventKind
                && mTaskId == that.mTaskId
                && mDurationInMillis == that.mDurationInMillis
                && mExampleSize == that.mExampleSize
                && mDataTransferDurationMillis == that.mDataTransferDurationMillis
                && mBytesUploaded == that.mBytesUploaded
                && mBytesDownloaded == that.mBytesDownloaded;
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + Long.hashCode(mClientVersion);
        _hash = 31 * _hash + mEventKind;
        _hash = 31 * _hash + Long.hashCode(mTaskId);
        _hash = 31 * _hash + Long.hashCode(mDurationInMillis);
        _hash = 31 * _hash + Long.hashCode(mExampleSize);
        _hash = 31 * _hash + Long.hashCode(mDataTransferDurationMillis);
        _hash = 31 * _hash + Long.hashCode(mBytesUploaded);
        _hash = 31 * _hash + Long.hashCode(mBytesDownloaded);
        return _hash;
    }

    /** A builder for {@link TrainingEventReported} */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static class Builder {

        private long mClientVersion;
        private int mEventKind;
        private long mTaskId;
        private long mDurationInMillis;
        private long mExampleSize;
        private long mDataTransferDurationMillis;
        private long mBytesUploaded;
        private long mBytesDownloaded;

        private long mBuilderFieldsSet = 0L;

        public Builder() {}

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setClientVersion(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mClientVersion = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setEventKind(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mEventKind = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setTaskId(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mTaskId = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setDurationInMillis(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8;
            mDurationInMillis = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleSize(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x10;
            mExampleSize = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setDataTransferDurationMillis(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x20;
            mDataTransferDurationMillis = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setBytesUploaded(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x40;
            mBytesUploaded = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setBytesDownloaded(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x80;
            mBytesDownloaded = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull TrainingEventReported build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x100; // Mark builder used

            TrainingEventReported o =
                    new TrainingEventReported(
                            mClientVersion,
                            mEventKind,
                            mTaskId,
                            mDurationInMillis,
                            mExampleSize,
                            mDataTransferDurationMillis,
                            mBytesUploaded,
                            mBytesDownloaded);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x100) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1704853284615L,
            codegenVersion = "1.0.23",
            sourceFile =
                    "packages/modules/OnDevicePersonalization/federatedcompute/src/com/android/federatedcompute/services/statsd/TrainingEventReported.java",
            inputSignatures =
                    "private  long mClientVersion\n"
                        + "private  int mEventKind\n"
                        + "private  long mTaskId\n"
                        + "private  long mDurationInMillis\n"
                        + "private  long mExampleSize\n"
                        + "private  long mDataTransferDurationMillis\n"
                        + "private  long mBytesUploaded\n"
                        + "private  long mBytesDownloaded\n"
                        + "class TrainingEventReported extends java.lang.Object implements []\n"
                        + "@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true,"
                        + " genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}

    // @formatter:on
    // End of generated code

}
