/*
 * Copyright (C) 2024 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.federatedcompute.services.statsd;

import com.android.ondevicepersonalization.internal.util.DataClass;

/**
 * Class holds FederatedComputeTrainingEventReported defined at
 * frameworks/proto_logging/stats/atoms/federatedcompute/federatedcompute_extension_atoms.proto
 */
@DataClass(genBuilder = true, genEqualsHashCode = true)
public class TrainingEventReported {
    private long mClientVersion;
    private int mEventKind;
    private long mPopulationId;
    private long mTaskId;
    private long mDurationInMillis;

    private long mExampleCount = 0;
    private long mExampleSize = 0;
    private long mDataTransferDurationMillis = 0;
    private long mBytesUploaded = 0;
    private long mBytesDownloaded = 0;

    private long mKeyAttestationLatencyMillis = 0;
    private long mExampleStoreBindLatencyNanos = 0;
    private long mExampleStoreStartQueryLatencyNanos = 0;

    // Code below generated by codegen v1.0.23.
    //
    // DO NOT MODIFY!
    // CHECKSTYLE:OFF Generated code
    //
    // To regenerate run:
    // $ codegen
    // $ANDROID_BUILD_TOP/packages/modules/OnDevicePersonalization/federatedcompute/src/com/android/federatedcompute/services/statsd/TrainingEventReported.java
    //
    // To exclude the generated code from IntelliJ auto-formatting enable (one-time):
    //   Settings > Editor > Code Style > Formatter Control
    // @formatter:off

    @DataClass.Generated.Member
    /* package-private */ TrainingEventReported(
            long clientVersion,
            int eventKind,
            long populationId,
            long taskId,
            long durationInMillis,
            long exampleCount,
            long exampleSize,
            long dataTransferDurationMillis,
            long bytesUploaded,
            long bytesDownloaded,
            long keyAttestationLatencyMillis,
            long exampleStoreBindLatencyNanos,
            long exampleStoreStartQueryLatencyNanos) {
        this.mClientVersion = clientVersion;
        this.mEventKind = eventKind;
        this.mPopulationId = populationId;
        this.mTaskId = taskId;
        this.mDurationInMillis = durationInMillis;
        this.mExampleCount = exampleCount;
        this.mExampleSize = exampleSize;
        this.mDataTransferDurationMillis = dataTransferDurationMillis;
        this.mBytesUploaded = bytesUploaded;
        this.mBytesDownloaded = bytesDownloaded;
        this.mKeyAttestationLatencyMillis = keyAttestationLatencyMillis;
        this.mExampleStoreBindLatencyNanos = exampleStoreBindLatencyNanos;
        this.mExampleStoreStartQueryLatencyNanos = exampleStoreStartQueryLatencyNanos;

        // onConstructed(); // You can define this method to get a callback
    }

    @DataClass.Generated.Member
    public long getClientVersion() {
        return mClientVersion;
    }

    @DataClass.Generated.Member
    public int getEventKind() {
        return mEventKind;
    }

    @DataClass.Generated.Member
    public long getPopulationId() {
        return mPopulationId;
    }

    @DataClass.Generated.Member
    public long getTaskId() {
        return mTaskId;
    }

    @DataClass.Generated.Member
    public long getDurationInMillis() {
        return mDurationInMillis;
    }

    @DataClass.Generated.Member
    public long getExampleCount() {
        return mExampleCount;
    }

    @DataClass.Generated.Member
    public long getExampleSize() {
        return mExampleSize;
    }

    @DataClass.Generated.Member
    public long getDataTransferDurationMillis() {
        return mDataTransferDurationMillis;
    }

    @DataClass.Generated.Member
    public long getBytesUploaded() {
        return mBytesUploaded;
    }

    @DataClass.Generated.Member
    public long getBytesDownloaded() {
        return mBytesDownloaded;
    }

    @DataClass.Generated.Member
    public long getKeyAttestationLatencyMillis() {
        return mKeyAttestationLatencyMillis;
    }

    @DataClass.Generated.Member
    public long getExampleStoreBindLatencyNanos() {
        return mExampleStoreBindLatencyNanos;
    }

    @DataClass.Generated.Member
    public long getExampleStoreStartQueryLatencyNanos() {
        return mExampleStoreStartQueryLatencyNanos;
    }

    @Override
    @DataClass.Generated.Member
    public boolean equals(@android.annotation.Nullable Object o) {
        // You can override field equality logic by defining either of the methods like:
        // boolean fieldNameEquals(TrainingEventReported other) { ... }
        // boolean fieldNameEquals(FieldType otherValue) { ... }

        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        @SuppressWarnings("unchecked")
        TrainingEventReported that = (TrainingEventReported) o;
        //noinspection PointlessBooleanExpression
        return true
                && mClientVersion == that.mClientVersion
                && mEventKind == that.mEventKind
                && mPopulationId == that.mPopulationId
                && mTaskId == that.mTaskId
                && mDurationInMillis == that.mDurationInMillis
                && mExampleCount == that.mExampleCount
                && mExampleSize == that.mExampleSize
                && mDataTransferDurationMillis == that.mDataTransferDurationMillis
                && mBytesUploaded == that.mBytesUploaded
                && mBytesDownloaded == that.mBytesDownloaded
                && mKeyAttestationLatencyMillis == that.mKeyAttestationLatencyMillis
                && mExampleStoreBindLatencyNanos == that.mExampleStoreBindLatencyNanos
                && mExampleStoreStartQueryLatencyNanos == that.mExampleStoreStartQueryLatencyNanos;
    }

    @Override
    @DataClass.Generated.Member
    public int hashCode() {
        // You can override field hashCode logic by defining methods like:
        // int fieldNameHashCode() { ... }

        int _hash = 1;
        _hash = 31 * _hash + Long.hashCode(mClientVersion);
        _hash = 31 * _hash + mEventKind;
        _hash = 31 * _hash + Long.hashCode(mPopulationId);
        _hash = 31 * _hash + Long.hashCode(mTaskId);
        _hash = 31 * _hash + Long.hashCode(mDurationInMillis);
        _hash = 31 * _hash + Long.hashCode(mExampleCount);
        _hash = 31 * _hash + Long.hashCode(mExampleSize);
        _hash = 31 * _hash + Long.hashCode(mDataTransferDurationMillis);
        _hash = 31 * _hash + Long.hashCode(mBytesUploaded);
        _hash = 31 * _hash + Long.hashCode(mBytesDownloaded);
        _hash = 31 * _hash + Long.hashCode(mKeyAttestationLatencyMillis);
        _hash = 31 * _hash + Long.hashCode(mExampleStoreBindLatencyNanos);
        _hash = 31 * _hash + Long.hashCode(mExampleStoreStartQueryLatencyNanos);
        return _hash;
    }

    /** A builder for {@link TrainingEventReported} */
    @SuppressWarnings("WeakerAccess")
    @DataClass.Generated.Member
    public static class Builder {

        private long mClientVersion;
        private int mEventKind;
        private long mPopulationId;
        private long mTaskId;
        private long mDurationInMillis;
        private long mExampleCount;
        private long mExampleSize;
        private long mDataTransferDurationMillis;
        private long mBytesUploaded;
        private long mBytesDownloaded;
        private long mKeyAttestationLatencyMillis;
        private long mExampleStoreBindLatencyNanos;
        private long mExampleStoreStartQueryLatencyNanos;

        private long mBuilderFieldsSet = 0L;

        public Builder() {}

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setClientVersion(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1;
            mClientVersion = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setEventKind(int value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2;
            mEventKind = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setPopulationId(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x4;
            mPopulationId = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setTaskId(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x8;
            mTaskId = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setDurationInMillis(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x10;
            mDurationInMillis = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleCount(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x20;
            mExampleCount = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleSize(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x40;
            mExampleSize = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setDataTransferDurationMillis(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x80;
            mDataTransferDurationMillis = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setBytesUploaded(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x100;
            mBytesUploaded = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setBytesDownloaded(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x200;
            mBytesDownloaded = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setKeyAttestationLatencyMillis(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x400;
            mKeyAttestationLatencyMillis = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleStoreBindLatencyNanos(long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x800;
            mExampleStoreBindLatencyNanos = value;
            return this;
        }

        @DataClass.Generated.Member
        public @android.annotation.NonNull Builder setExampleStoreStartQueryLatencyNanos(
                long value) {
            checkNotUsed();
            mBuilderFieldsSet |= 0x1000;
            mExampleStoreStartQueryLatencyNanos = value;
            return this;
        }

        /** Builds the instance. This builder should not be touched after calling this! */
        public @android.annotation.NonNull TrainingEventReported build() {
            checkNotUsed();
            mBuilderFieldsSet |= 0x2000; // Mark builder used

            if ((mBuilderFieldsSet & 0x20) == 0) {
                mExampleCount = 0;
            }
            if ((mBuilderFieldsSet & 0x40) == 0) {
                mExampleSize = 0;
            }
            if ((mBuilderFieldsSet & 0x80) == 0) {
                mDataTransferDurationMillis = 0;
            }
            if ((mBuilderFieldsSet & 0x100) == 0) {
                mBytesUploaded = 0;
            }
            if ((mBuilderFieldsSet & 0x200) == 0) {
                mBytesDownloaded = 0;
            }
            if ((mBuilderFieldsSet & 0x400) == 0) {
                mKeyAttestationLatencyMillis = 0;
            }
            if ((mBuilderFieldsSet & 0x800) == 0) {
                mExampleStoreBindLatencyNanos = 0;
            }
            if ((mBuilderFieldsSet & 0x1000) == 0) {
                mExampleStoreStartQueryLatencyNanos = 0;
            }
            TrainingEventReported o =
                    new TrainingEventReported(
                            mClientVersion,
                            mEventKind,
                            mPopulationId,
                            mTaskId,
                            mDurationInMillis,
                            mExampleCount,
                            mExampleSize,
                            mDataTransferDurationMillis,
                            mBytesUploaded,
                            mBytesDownloaded,
                            mKeyAttestationLatencyMillis,
                            mExampleStoreBindLatencyNanos,
                            mExampleStoreStartQueryLatencyNanos);
            return o;
        }

        private void checkNotUsed() {
            if ((mBuilderFieldsSet & 0x2000) != 0) {
                throw new IllegalStateException(
                        "This Builder should not be reused. Use a new Builder instance instead");
            }
        }
    }

    @DataClass.Generated(
            time = 1711822248905L,
            codegenVersion = "1.0.23",
            sourceFile =
                    "packages/modules/OnDevicePersonalization/federatedcompute/src/com/android/federatedcompute/services/statsd/TrainingEventReported.java",
            inputSignatures =
                    "private  long mClientVersion\nprivate  int mEventKind\nprivate  long mPopulationId\nprivate  long mTaskId\nprivate  long mDurationInMillis\nprivate  long mExampleCount\nprivate  long mExampleSize\nprivate  long mDataTransferDurationMillis\nprivate  long mBytesUploaded\nprivate  long mBytesDownloaded\nprivate  long mKeyAttestationLatencyMillis\nprivate  long mExampleStoreBindLatencyNanos\nprivate  long mExampleStoreStartQueryLatencyNanos\nclass TrainingEventReported extends java.lang.Object implements []\n@com.android.ondevicepersonalization.internal.util.DataClass(genBuilder=true, genEqualsHashCode=true)")
    @Deprecated
    private void __metadata() {}

    // @formatter:on
    // End of generated code

}
